# Generated by Django 3.0.6 on 2020-05-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
