# Generated by Django 3.0.6 on 2020-05-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200505_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('middle', 'Middle'), ('large', 'Large')], default='small', max_length=10),
        ),
    ]
