# Generated by Django 3.0.6 on 2020-05-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('middle', 'Middle'), ('large', 'Large'), ('extra large', 'Extra Large')], default='small', max_length=15),
        ),
    ]
